### ISSUE TITLE
download link is broken

### ISSUE THREAD

**Issue by kyungyunlee** [gabolsgabs/DALI#1]
Hi!
I am interested in checking out the dataset, but the download link seems to be broken...
Maybe I should wait a few more days, but just checking if it is supposed to be working now. 
Thanks for the dataset :)

**Comment by gabolsgabs** [comment]
Hello Kyungyun,
Thanks for your interest in DALI. The dataset is not available yet. That's the main reason the link is broken. We will launch it pretty soon (hopefully at the end of this week). We will send an email to the ISMIR community mailing list.

**Comment by gabolsgabs** [comment]
Now it's working. You can ask for your pass at:

https://github.com/gabolsgabs/DALI/tree/master/versions
