### ISSUE TITLE
Code for the dataset creation

### ISSUE THREAD

**Issue by Demfier** [gabolsgabs/DALI#3]
Hi @gabolsgabs,

Are you gonna be releasing the code you used to create the dataset anytime soon? It would really help if you do.

Thanks,
Gaurav.

**Comment by gabolsgabs** [comment]
Hello Gaurav.

Yep. Some part of the code used for the dataset creation will be available soon. Which part in particular are you interested? We will add SVP computation (providing a model precomputed) and the NCC functions.

Regards,
Gabriel

**Comment by Demfier** [comment]
Thank you for the prompt response, Gabriel. I was interested in the code for the teacher-student paradigm you've proposed. I am trying to adapt it to a different dataset for a research project. So was wondering if you could release your code.

Let me know if that would be possible and by what time we could expect it.

Thanks again,
Gaurav.

**Comment by gabolsgabs** [comment]
Hello Gaurav,

Sorry for the delay. I see. There is not special code for the teacher-student paradigm. For each new SVP version we re-train from scratch the same architecture. The only difference is the input-target data.  

For the teacher we used MedleyDB and Jamendo and for the student DALI (a previous version not released with the annotated aligned worse than this one) after being align with the NCC.

I hope this clarify your question.
Gabriel
