### ISSUE TITLE
ground truth of notes

### ISSUE THREAD

**Issue by rynerisraid** [gabolsgabs/DALI#4]
Hi,
Thank you for the wonderful dataset.
I found that the annotatioms of 'notes' missing through entry.annotations['annot']['notes']. Is there any update in ground truth file.

Thanks
Lin

**Comment by gabolsgabs** [comment]
Hello Lin,

I'm not quite sure to understand your problem. Can't load annotation files? Is that a particular file that has no annotations? Could you provide some code to reproduce what you are experiencing?

Note that the ground-truth file only contains the manual annotations for the two parameters that define the global alignment but not the annotations themselves. These are at https://zenodo.org/record/2577915

Thanks

**Comment by rynerisraid** [comment]
I'm sorry to bother you that I confuse the keys for the horizontal and vertical situation:
->['notes', 'lines', 'words', 'paragraphs']
->['hierarchical']['text']

Thanks

**Comment by gabolsgabs** [comment]
No worries. Not hesitate to ask if you have further issues. 

Regards.
