### ISSUE TITLE
Question about get_audio

### ISSUE THREAD

**Issue by zhr147147** [gabolsgabs/DALI#6]
Hi @gabolsgabs, 

I'm interested in the dataset. But I meet a question when I plan to get audio.
When I run 
`errors = dali_code.get_audio(dali_info, path_audio, skip=[], keep=[])`
I get the error:

> ERROR: ffmpeg exited with code 1
> ERROR: ffmpeg exited with code 1
> [tcp @ 000001a58d41b640] Connection to tcp://r2---sn-gxuo03g-3c2e.googlevideo.com:443 failed: Error number -138 occurred
> https://r2---sn-gxuo03g-3c2e.googlevideo.com/videoplayback?expire=1628760487&ei=R5UUYaOuGLmOsfIPtdWXiA8&ip=72.13.86.178&id=o-ACsbiYNB_jkjhjaAhmR3Inb0Gt9_V6ZaKJ1kpdAZdrQ3&itag=251&source=youtube&requiressl=yes&mh=j6&mm=31%2C29&mn=sn-gxuo03g-3c2e%2Csn-n4v7sn7l&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=2487500&vprv=1&mime=audio%2Fwebm&ns=dGRvWmr4u0kSGji0arhIxuwG&gir=yes&clen=5002463&dur=282.861&lmt=1573450506527303&mt=1628738444&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=1301222&n=O9L5WR7rYM1WvfV5aP5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgF5z4QMeCv8k9PtHFjGv4I27RLLG7caPJ5ybflZ0CAz0CIQDzYqp8QXh1ynjeWQSPxm-ZyZljZaNsQRBOaarv_6YPvg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgLgzLM0HccljQ96vQk-zmtgTyjUcPvNNpF8ZGM7CwE0QCIFz42uRHnpZDpFtwCanHwheTaBzWJ7uDsKxOqbd-KtzS: Unknown error

I can open the link above by my browser, so I try to close the firewall but the error is still there.
I'd appreciate it if you could help me.

Thank you,
Haoran

**Comment by gabolsgabs** [comment]
Hello @zhr147147,

Thanks for the report. Is this error happening for a particular id (you are able to get some audio files) or is it something consistent for all of them (you cannot get any audio)? which dataset version are you using? 

Regards,
Gabriel

**Comment by zhr147147** [comment]
Hi, gabolsgabs,

Thanks for your reply

I cannot get any audio, this problem may be caused by my network condition.
